Chart0_0:
  E_max: 200.0
  E_min: 1.0
  chart_type: PhasePlot
  cnorm_type: Log
  cpow_num: 0.6
  face_color: gainsboro
  interpolation: nearest
  masked: 1
  mom_dim: 0
  prtl_type: ions
  set_E_max: false
  set_E_min: false
  set_v_max: false
  set_v_min: false
  set_y_max: false
  set_y_min: false
  show_cbar: true
  show_int_region: true
  show_shock: false
  spatial_x: true
  spatial_y: false
  twoD: 1
  v_max: 0
  v_min: -2.0
  weighted: false
  weights: null
  x_bins: 200
  x_val: x
  y_bins: 200
  y_max: 2
  y_min: -2.0
  y_val: px
Chart0_1:
  sim_num: 0
  E_max: 200.0
  E_min: 1.0
  chart_type: PhasePlot
  cnorm_type: Log
  cpow_num: 0.6
  face_color: gainsboro
  interpolation: nearest
  masked: 1
  mom_dim: 0
  prtl_type: electrons
  set_E_max: false
  set_E_min: false
  set_v_max: false
  set_v_min: false
  set_y_max: false
  set_y_min: false
  show_cbar: true
  show_int_region: true
  show_shock: false
  spatial_x: true
  spatial_y: false
  twoD: 1
  v_max: 0
  v_min: -2.0
  weighted: false
  weights: null
  x_bins: 200
  x_val: x
  y_bins: 200
  y_max: 2
  y_min: -2.0
  y_val: px
Chart1_0:
  OutlineText: true
  UseDivCmap: false
  chart_type: ScalarFlds
  cmap: None
  cnorm_type: Linear
  cpow_num: 0.6
  div_midpoint: 0.0
  face_color: gainsboro
  flds_type: density
  interpolation: bicubic
  normalize_density: true
  set_color_limits: false
  set_v_max: false
  set_v_min: false
  show_cbar: true
  show_cpu_domains: false
  show_labels: true
  show_shock: false
  spatial_x: true
  spatial_y: 0
  stretch_colors: false
  twoD: 0
  v_max: 10
  v_min: 0
Chart1_1:
  OutlineText: true
  UseDivCmap: true
  chart_type: VectorFlds
  cmap: None
  cnorm_type: Linear
  cpow_num: 1.0
  div_midpoint: 0.0
  face_color: gainsboro
  field_type: B
  interpolation: bicubic
  normalize_fields: true
  set_v_max: false
  set_v_min: false
  show_FFT_region: false
  show_cbar: true
  show_cpu_domains: false
  show_labels: true
  show_shock: false
  show_x: 1
  show_y: 1
  show_z: 1
  spatial_x: true
  spatial_y: false
  stretch_colors: false
  twoD: 0
  v_max: 10
  v_min: 0
MainParamDict:
  2DSlicePlane: 0
  # Average1D: 0
  AxLabelSize: 11
  ClearFig: true
  cmaps_with_green:
  - viridis
  - Rainbow + White
  - Blue/Green/Red/Yellow
  - Cube YF
  - Linear_L
  ColorMap: Blue/Green/Red/Yellow
  # ConstantShockVel: true
  DivColorMap: Blue/Green/Red/Yellow
  FFT_color: k
  FigSize:
  - 12.0
  - 6.22
  HAxesExtent:
  - 18
  - 92
  - 0
  - -1
  HCbarExtent:
  - 0
  - 4
  - 0
  - -1
  HSubPlotParams:
    bottom: 0.06
    hspace: 0.3
    left: 0.06
    right: 0.95
    top: 0.91
    wspace: 0.15
  HorizontalCbars: false
  ImageAspect: 0
  # LinkSpatial: 2
  LoopPlayback: true
  MaxCols: 8
  MaxRows: 8
  NumFontSize: 11
  NumOfCols: 2
  NumOfRows: 2
  # PrtlStride: 1
  Recording: false
  Reload2End: true
  SetxLim: false
  SetyLim: false
  ShowTitle: true
  SkipSize: 5
  VAxesExtent:
  - 4
  - 90
  - 0
  - 92
  VCbarExtent:
  - 4
  - 90
  - 94
  - 97
  VSubPlotParams:
    bottom: 0.06
    hspace: 0.15
    left: 0.06
    right: 0.95
    top: 0.93
    wspace: 0.23
  WaitTime: 0.01
  WindowSize: 1200x700
  annotateTextSize: 18
  cbarLabelPad: 15
  dpi: 100
  electron_color: '#fca636'
  electron_fit_color: yellow
  ion_color: '#d6556d'
  ion_fit_color: r
  legendLabelSize: 11
  xLabelPad: 0
  xLeft: 0.0
  xRight: 100.0
  yBottom: 0.0
  yLabelPad: 0
  yTop: 100.0
  LinkSpatial: 2
  ySlice: 0.5
  zSlice: 0.5
  xSlice: 0.0
  xLimsRelative: false
  Average1D: false
  PrtlStride: 1
  2DSlicePlane: 0

general:
  ConfigName: Default
